# Generated by Django 5.0.6 on 2024-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField(unique=True)),
                ('href', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('loc', models.TextField(blank=True)),
            ],
        ),
    ]
