# Generated by Django 5.0.6 on 2024-06-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_resume_vacancy_is_active_vacancy_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='res_id',
            new_name='out_id',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_id',
            new_name='out_id',
        ),
    ]
