# Generated by Django 5.0.6 on 2024-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_resume_bio_alter_resume_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_id', models.BigIntegerField(unique=True)),
                ('href', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('exp', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('last', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='HHVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_id', models.BigIntegerField(unique=True)),
                ('href', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('salary_from', models.BigIntegerField(blank=True, null=True)),
                ('salary_to', models.BigIntegerField(blank=True, null=True)),
                ('metro', models.CharField(blank=True, max_length=255, null=True)),
                ('req', models.TextField(blank=True, null=True)),
                ('resp', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-time_created']},
        ),
    ]
