# Generated by Django 5.0.6 on 2024-06-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_hhresume_hhvacancy_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hhvacancy',
            old_name='city',
            new_name='area',
        ),
    ]
