# Generated by Django 5.0.6 on 2024-06-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_hhresume_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
