# Generated by Django 5.0.6 on 2024-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_resume_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhvacancy',
            name='employment',
            field=models.BooleanField(blank=True, choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Проектная работа'), (3, 'Волонтерство'), (4, 'Стажировка')], null=True),
        ),
        migrations.AddField(
            model_name='hhvacancy',
            name='experience',
            field=models.BooleanField(blank=True, choices=[(0, 'Нет опыта'), (1, 'От 1 года до 3 лет'), (2, 'От 3 до 6 лет'), (3, 'Более 6 лет')], null=True),
        ),
    ]
