# Generated by Django 5.0.6 on 2024-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_hhvacancy_employment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hhvacancy',
            options={'ordering': ['-time_updated']},
        ),
        migrations.AlterField(
            model_name='hhvacancy',
            name='experience',
            field=models.CharField(blank=True, choices=[('noExperience', 'Без опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='noExperience', max_length=30, null=True),
        ),
    ]
