# Generated by Django 5.0.6 on 2024-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_hhvacancy_options_alter_hhvacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhresume',
            name='employment',
            field=models.CharField(blank=True, choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('project', 'Проектная работа'), ('volunteer', 'Волонтерство'), ('probation', 'Стажировка')], default='full', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hhresume',
            name='experience',
            field=models.CharField(blank=True, choices=[('noExperience', 'Без опыта'), ('between1And3', 'От 1 года до 3 лет'), ('between3And6', 'От 3 до 6 лет'), ('moreThan6', 'Более 6 лет')], default='noExperience', max_length=30, null=True),
        ),
    ]
