# Generated by Django 5.0.6 on 2024-07-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_hhresume_employment_hhresume_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hhresume',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='hhresume',
            name='experience',
        ),
    ]
