# Generated by Django 5.0.6 on 2024-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_hhresume_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhresume',
            name='exp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hhresume',
            name='href',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hhresume',
            name='last',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hhvacancy',
            name='area',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hhvacancy',
            name='href',
            field=models.CharField(max_length=500),
        ),
    ]
